### ISSUE TITLE
Browser process freezes when zooming past zoomlevel 16

### ISSUE THREAD

**Issue by sharppaul** [FacilMap/Leaflet.AutoGraticule#1]
Hi, great plugin, really simple to use! However I'm running into an issue where the browser process freezes after zooming past level 16 (15 for firefox). 

I don't get any error messages, so it's hard for me to test further. The browser tab just freezes completely and will not recover.

[Example (js fiddle)](https://jsfiddle.net/ndr9zkx8/)

This also happens in your own example:

[https://unpkg.com/leaflet-auto-graticule@1.1.1/example.html](https://unpkg.com/leaflet-auto-graticule@1.1.1/example.html)

**Comment by cdauth** [comment]
Thanks for reporting, good catch! I think this was caused by the fact that the coordinate divisor was rounded to 2 decimal digits, so when you zoomed in to a point where the divisor got to 0.002, it got rounded to 0, causing an infinite loop when drawing the latitude lines. I have fixed it to support smaller divisors, so the infinite loop should be fixed (and coordinates with 3 decimals or more are displayed properly).
